# Generated by Django 2.2.9 on 2020-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotTopicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotLink', models.CharField(max_length=300)),
                ('hotTitle', models.CharField(max_length=50)),
            ],
        ),
    ]
