# Generated by Django 2.2.9 on 2020-03-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottopicinfo',
            name='crawlTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hottopicinfo',
            name='hotIndex',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='hottopicinfo',
            name='hotReadNum',
            field=models.IntegerField(default=-1),
        ),
    ]
