# Generated by Django 2.2.9 on 2020-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboreach', '0002_auto_20200326_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentId', models.CharField(max_length=20)),
                ('crawlTime', models.IntegerField(default=0)),
                ('weiboUrl', models.CharField(max_length=50)),
                ('commentUserId', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=150)),
                ('createdAt', models.CharField(max_length=20)),
                ('likeNum', models.IntegerField(default=0)),
                ('tool', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InfoId', models.CharField(max_length=20)),
                ('crawlTime', models.IntegerField(default=0)),
                ('personUrl', models.CharField(max_length=50)),
                ('nickName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=10)),
                ('briefIntroduction', models.CharField(max_length=140)),
                ('birthday', models.CharField(max_length=15)),
                ('vipLevel', models.CharField(max_length=10)),
                ('authentication', models.CharField(max_length=100)),
                ('weiboNum', models.IntegerField(default=0)),
                ('followsNum', models.IntegerField(default=0)),
                ('fansNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RepostId', models.CharField(max_length=30)),
                ('crawlTime', models.IntegerField(default=0)),
                ('weiboUrl', models.CharField(max_length=50)),
                ('repostUrl', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=150)),
                ('tool', models.CharField(max_length=30)),
                ('createdAt', models.CharField(max_length=20)),
                ('likeNum', models.IntegerField(default=0)),
                ('repostLevel', models.IntegerField(default=0)),
                ('repostUserId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeiboPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostId', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=50)),
                ('weiboUrl', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('createdAt', models.CharField(max_length=20)),
                ('tool', models.CharField(max_length=30)),
                ('crawlTime', models.IntegerField(default=0)),
                ('userId', models.CharField(max_length=20)),
                ('repostNum', models.IntegerField(default=0)),
                ('likeNum', models.IntegerField(default=0)),
                ('commentNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='hottopicinfo',
            name='hotReadNum',
            field=models.IntegerField(default=0),
        ),
    ]
