# Generated by Django 2.2.9 on 2020-04-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboreach', '0004_remove_hottopicinfo_crawltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='repost',
            name='content',
            field=models.TextField(),
        ),
    ]
