# Generated by Django 2.2.9 on 2020-04-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboreach', '0005_auto_20200402_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='briefIntroduction',
            field=models.TextField(),
        ),
    ]
