# Generated by Django 2.2.9 on 2020-04-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weiboreach', '0006_auto_20200403_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='briefIntroduction',
        ),
    ]
