# Generated by Django 2.2.9 on 2020-04-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weiboreach', '0003_auto_20200402_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hottopicinfo',
            name='crawlTime',
        ),
    ]
