# Generated by Django 2.2.9 on 2020-04-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboreach', '0007_remove_information_briefintroduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibopost',
            name='isRepost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weibopost',
            name='originWeibo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
